/**
 * TestAngularSwagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OkStatus { 
    isOk?: boolean;
    nr?: number;
    error?: string | null;
}

